RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
OLED_ENABLE=no
MAGIC_ENABLE = no
CONSOLE_ENABLE=no
COMMAND_ENABLE=no
SPACE_CADET_ENABLE=no
GRAVE_ESC_ENABLE=no

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE=yes
CAPS_WORD_ENABLE=yes

TAP_DANCE_ENABLE = yes

